### ISSUE TITLE
Missing variables in PaymentMethods Model and other data inconsistencies

### ISSUE THREAD

**Issue by devarx** [klix-app/merchant-api-php#3]
Hello!

In integration process with Klix I've found that some variables aren't included in Models. For example - PaymentMethods model doesn't have 'logos' and 'payment_method_groups' variables. Can you please check all models and update them?

**Comment by devarx** [comment]
Next issue found about model variables - In POST (/purchases/) request body wants - 'payment_method_whitelist', but in Purchase model there is field called 'payment_methods_whitelist', so at the moment whitelisted payment methods aren't working

**Comment by JackDev42** [comment]
Hello,

Those issues are already solved with new release **3.0.1**
