### ISSUE TITLE
Possibility to provide language in getPaymentMethods() and incorrect @return field

### ISSUE THREAD

**Issue by devarx** [klix-app/merchant-api-php#5]
In Regular GET request, there can be added 
'language' => $language,aside 'currency'
Is there possibility you could add this option to getPaymentMethods()?

**Comment by devarx** [comment]
There is no such PaymentMethods that is provided at @return field, there should be \Klix\Model\PaymentMethods

**Comment by JackDev42** [comment]
> In Regular GET request, there can be added
'language' => $language,aside 'currency'
Is there possibility you could add this option to getPaymentMethods()?

Language is not needed (have no affect) on getting payment methods.
Language is needed only when creating purchase.

> There is no such PaymentMethods that is provided at @return field, there should be \Klix\Model\PaymentMethods

issue fixed. please update package
