### ISSUE TITLE
No possibility to add optional fields on getPaymentMethods

### ISSUE THREAD

**Issue by devarx** [klix-app/merchant-api-php#6]
Is there any chance you could add optional field array or something to make possibe to add optional fields on getPaymentMethods function?

![image](https://user-images.githubusercontent.com/41114642/167568946-e96548bc-4018-49ff-993e-7b80112c8a7b.png)

**Comment by JackDev42** [comment]
We updated the library. 
Issue is fixed in 3.0.4.

**Comment by devarx** [comment]
Wrong @return type for getPaymentMethods() in 3.0.4

**Comment by JackDev42** [comment]
return type fixed in 3.0.5
